"""
Filename: 06b_example_simple_pandapipes_osmnx.py
Author: Dipl.-Ing. (FH) Jonas Pfeiffer
Date: 2025-11-22
Description: Test pandapipes simulation with OSMnx-generated network data from 05b.
             Imports GeoJSON files generated by OSMnx Steiner Tree approach.

Usage: Run the script after generating network with 05b_example_net_generation_osmnx.py

Example:
    $ python 06b_example_simple_pandapipes_osmnx.py
"""

import logging
import os
import traceback

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import geopandas as gpd
import pandapipes as pp
import pandapipes.plotting as pp_plot

from districtheatingsim.net_simulation_pandapipes.pp_net_initialisation_geojson import *
from districtheatingsim.net_simulation_pandapipes.utilities import *
from districtheatingsim.net_simulation_pandapipes.interactive_network_plot import InteractiveNetworkPlot

# Initialize logging
logging.basicConfig(level=logging.INFO)


def initialize_net_from_osmnx_geojson(
    supply_file: str,
    return_file: str,
    hast_file: str,
    generator_file: str,
    supply_temperature: float = 85.0,
    flow_pressure_pump: float = 4.0,
    lift_pressure_pump: float = 1.5,
    qext_w: np.ndarray = None,
    return_temperature: np.ndarray = None,
    min_supply_temperature: np.ndarray = None,
    pipetype: str = "KMR 100/250-2v",
    v_max_m_s: float = 1.5,
    k_mm: float = 0.1
):
    """
    Initialize pandapipes network from unified GeoJSON network file.
    
    Note: Use NetworkGeoJSONSchema.split_to_legacy_format() to extract individual layers.
    
    Parameters
    ----------
    supply_file : str
        Path to flow line GeoJSON (or extract from unified format)
    return_file : str
        Path to return line GeoJSON (or extract from unified format)
    hast_file : str
        Path to building connections GeoJSON (contains cross-connections WITH building data)
    generator_file : str
        Path to generator connections GeoJSON
    supply_temperature : float
        Supply temperature in °C (default: 85)
    flow_pressure_pump : float
        Pump flow pressure in bar (default: 4.0)
    lift_pressure_pump : float
        Pump lift pressure in bar (default: 1.5)
    qext_w : np.ndarray
        Heat demand for each consumer in W (default: 50kW per consumer)
    return_temperature : np.ndarray
        Return temperature for each consumer in °C (default: 55°C)
    min_supply_temperature : np.ndarray
        Minimum supply temperature for each consumer in °C (default: 60°C)
    pipetype : str
        Pipe standard type (default: "110/202 PLUS")
    v_max_m_s : float
        Maximum flow velocity in m/s (default: 1.5)
    k_mm : float
        Pipe roughness in mm (default: 0.1)
        
    Returns
    -------
    pp.pandapipesNet
        Initialized pandapipes network
    """
    print(f"\n{'='*70}")
    print("PANDAPIPES NETWORK INITIALIZATION FROM OSMNX DATA")
    print(f"{'='*70}")
    
    # Check if files exist
    for file in [supply_file, return_file, hast_file, generator_file]:
        if not os.path.exists(file):
            raise FileNotFoundError(f"File not found: {file}")
    
    # Load GeoJSON files
    print("\nLoading GeoJSON files...")
    supply_gdf = gpd.read_file(supply_file)
    return_gdf = gpd.read_file(return_file)
    hast_gdf = gpd.read_file(hast_file)
    generator_gdf = gpd.read_file(generator_file)
    
    print(f"✓ Supply lines: {len(supply_gdf)}")
    print(f"✓ Return lines: {len(return_gdf)}")
    print(f"✓ HAST lines (with building data): {len(hast_gdf)}")
    print(f"✓ Generator: {len(generator_gdf)}")
    
    # Check if HAST contains building data
    if 'Wärmebedarf' in hast_gdf.columns:
        print(f"  → HAST contains building data (Wärmebedarf column found)")
    else:
        print(f"  ⚠ HAST missing building data columns!")
    
    # Set default heat demands and return temperatures if not provided
    n_consumers = len(hast_gdf)
    
    # Create empty pandapipes network
    net = pp.create_empty_network(fluid="water")
        
    print("\n" + "="*70)
    print("Building pandapipes network from GeoJSON data...")
    print("="*70)
    
    # Prepare data dictionaries for create_network function
    gdf_dict = {
        "flow_line": supply_gdf,
        "return_line": return_gdf,
        "heat_consumer": hast_gdf,
        "heat_producer": generator_gdf
    }
    
    print(return_temperature)
    consumer_dict = {
        "qext_w": qext_w,
        "min_supply_temperature_heat_consumer": np.full(n_consumers, min_supply_temperature),
        "return_temperature_heat_consumer": return_temperature
    }
    
    pipe_dict = {
        "pipetype": pipetype,
        "v_max_pipe": v_max_m_s,
        "material_filter": "KMR",
        "pipe_creation_mode": "type",
        "k_mm": k_mm
    }
    
    producer_dict = {
        "supply_temperature": supply_temperature,
        "flow_pressure_pump": flow_pressure_pump,
        "lift_pressure_pump": lift_pressure_pump,
        "main_producer_location_index": 0,
        "secondary_producers": None
    }
    
    # Use the existing create_network function
    net = create_network(gdf_dict, consumer_dict, pipe_dict, producer_dict)
    
    print(f"\n✓ Network created successfully!")
    print(f"  Junctions: {len(net.junction)}")
    print(f"  Pipes: {len(net.pipe)}")
    print(f"  Heat consumers: {len(net.heat_consumer)}")
    print(f"  Pumps: {len(net.circ_pump_pressure)}")

    # Optimize network sizing
    print("\nOptimizing network sizing...")
    net = optimize_diameter_types(
        net,
        v_max=v_max_m_s,
        material_filter="KMR",
        k=k_mm
    )

    print(f"\n✓ Network sizing optimization complete!")
    print(f"  Junctions: {len(net.junction)}")
    print(f"  Pipes: {len(net.pipe)}")
    print(f"  Heat consumers: {len(net.heat_consumer)}")
    print(f"  Pumps: {len(net.circ_pump_pressure)}")
    
    return net


def print_results(net):
    """Print network configuration and results."""
    print("\n" + "="*70)
    print("NETWORK CONFIGURATION")
    print("="*70)
    print("\nJunctions:")
    print(net.junction)
    print("\nPipes:")
    print(net.pipe)
    print("\nHeat Consumers:")
    print(net.heat_consumer)
    print("\nPumps:")
    print(net.circ_pump_pressure)
    
    print("\n" + "="*70)
    print("SIMULATION RESULTS")
    print("="*70)
    print("\nJunction Results:")
    print(net.res_junction)
    print("\nPipe Results:")
    print(net.res_pipe)
    print("\nHeat Consumer Results:")
    print(net.res_heat_consumer)
    print("\nPump Results:")
    print(net.res_circ_pump_pressure)


if __name__ == "__main__":
    try:
        from districtheatingsim.net_generation.network_geojson_schema import NetworkGeoJSONSchema
        import tempfile
        
        # Path to unified GeoJSON network file
        data_dir = "examples/data/osmnx_steiner_output"
        unified_file = os.path.join(data_dir, "Wärmenetz.geojson")
        
        # Load and split unified format
        unified_geojson = NetworkGeoJSONSchema.load_from_file(unified_file)
        supply_gdf, return_gdf, hast_gdf, generator_gdf = NetworkGeoJSONSchema.split_to_legacy_format(unified_geojson)
        
        # For function compatibility, save temporary files (or modify function to accept GeoDataFrames)
        temp_dir = tempfile.mkdtemp()
        supply_file = os.path.join(temp_dir, "supply.geojson")
        return_file = os.path.join(temp_dir, "return.geojson")
        hast_file = os.path.join(temp_dir, "hast.geojson")
        generator_file = os.path.join(temp_dir, "generator.geojson")
        
        supply_gdf.to_file(supply_file, driver="GeoJSON")
        return_gdf.to_file(return_file, driver="GeoJSON")
        hast_gdf.to_file(hast_file, driver="GeoJSON")
        generator_gdf.to_file(generator_file, driver="GeoJSON")
        
        # Initialize network from extracted data
        n_hast = len(hast_gdf)
        qext_w = np.full(n_hast, 50000.0)           # 50 kW per consumer
        return_temps = np.full(n_hast, 55.0)        # 55 °C return for each consumer

        net = initialize_net_from_osmnx_geojson(
            supply_file=supply_file,
            return_file=return_file,
            hast_file=hast_file,
            generator_file=generator_file,
            supply_temperature=90.0,
            flow_pressure_pump=4.0,
            lift_pressure_pump=2.0,
            qext_w=qext_w,
            return_temperature=return_temps,
            min_supply_temperature=60.0,
            pipetype="110/202 PLUS",
            v_max_m_s=1.5,
            k_mm=0.1
        )
        
        # Print results
        print_results(net)
        
        # Create interactive visualization
        print("\nGenerating interactive network visualization...")
        plot = InteractiveNetworkPlot(net, crs="EPSG:25833")
        fig = plot.create_interactive_plot_with_controls(
            basemap_style='carto-positron',
            colorscale='Viridis'
        )
        
        # Show plot in browser
        fig.show()
        
        print("\n" + "="*70)
        print("✓ SUCCESS: Network simulation completed")
        print("="*70)

    except Exception as e:
        print("\n" + "="*70)
        print("✗ ERROR: An error occurred")
        print("="*70)
        print(traceback.format_exc())
        raise e
